function pnew = change_parname(pname)
    if strcmp(pname, "kgut")
        pnew = "k_{gut}";
    elseif strcmp(pname, "V_plasma")
        pnew = "V_{plasma}";
    elseif strcmp(pname, "V_inter")
        pnew = "V_{inter}";
    elseif strcmp(pname, "V_muscle")
        pnew = "V_{intracellular}";
    elseif strcmp(pname, "m_K_ALDO")
        pnew = "m_K^{ALDO}";
    elseif strcmp(pname, "Km")
        pnew = "K_m";
    elseif strcmp(pname, "P_ECF")
        pnew = "P_{ECF}";
    elseif strcmp(pname, "dtKsec_eq")
        pnew = "\Phi_{dt-Ksec}^{eq}";
    elseif strcmp(pname, "A_dtKsec")
        pnew = "A_{dt-Ksec}";
    elseif strcmp(pname, "B_dtKsec")
        pnew = "B_{dt-Ksec}";
    elseif strcmp(pname, "cdKsec_eq")
        pnew = "\Phi_{cd-Ksec}^{eq}";
    elseif strcmp(pname, "A_cdKsec")
        pnew = "A_{cd-Ksec}";
    elseif strcmp(pname, "B_cdKsec")
        pnew = "B_{cd-Ksec}";
    elseif strcmp(pname, "A_cdKreab")
        pnew = "A_{cd-Kreab}";
    elseif strcmp(pname, "A_insulin")
        pnew = "A_{insulin}";
    elseif strcmp(pname, "B_insulin")
        pnew = "B_{insulin}";
    elseif strcmp(pname, "Vmax")
        pnew = "V_{max}";
    elseif strcmp(pname, "GFR")
        pnew = "\Phi_{GFR}";
    elseif strcmp(pname, "FF")
        pnew = "A_{Kin}";
    elseif strcmp(pname, "ALD_eq")
        pnew = "C_{al}^{base}";
    elseif strcmp(pname, "KMuscleBase")
        pnew = "K_{IC}^{base}";
    elseif strcmp(pname, "Kecf_base")
        pnew = "K_{ECF}^{base}";
    elseif strcmp(pname, "Phi_Kin_ss")
        pnew = "Phi_{Kin}^{ss}";
    elseif strcmp(pname, "etapsKreab")
        pnew = "\eta_{ps-Kreab}";
    else
        pnew = pname;
    end
end